language: java
jdk:
- openjdk8
branches:
  only:
  - develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dia0312@naver.com
before_install:
- openssl aes-256-cbc -K $encrypted_f728702889c9_key -iv $encrypted_f728702889c9_iv -in Secret.java.enc -out Secret.java -d
- openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv -in application.properties.enc -out application.properties -d
- mv Secret.java ~/build/Smileflower_Santa/Smileflower_Server/src/main/java/com/smileflower/santa/config/secret
- mv application.properties ~/build/Smileflower_Santa/Smileflower_Server/src/main/resources


