language: java
jdk:
- openjdk8
branches:
  only:
  - develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dia0312@naver.com
before_install:
- openssl aes-256-cbc -K $encrypted_12eaa4ded41a_key -iv $encrypted_12eaa4ded41a_iv
  -in ~/src/main/resources/config.tar.enc -out ~/src/main/resources/config.tar -d
- openssl aes-256-cbc -K $encrypted_2895d60e3414_key -iv $encrypted_2895d60e3414_iv
  -in ~/src/main/java/com/smileflower/santa/config/secret/secret.tar.enc -out ~/src/main/java/com/smileflower/santa/config/secret/secret.tar -d
- tar xvf ~/src/main/resources/config.tar
- tar xvf ~/src/main/java/com/smileflower/santa/config/secret/secret.tar

